In [1]:
import numpy as np

In [4]:
np.random.randint(1,5,(2,2))

array([[1, 2],
       [1, 3]])

In [5]:
np.random.randint(1,10,(3,3))

array([[6, 1, 6],
       [4, 5, 7],
       [4, 4, 7]])

In [6]:
np.random.randint(2, size=10)

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1])